name: "Commit Linter"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  lint-commits:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: gh pr checkout "$PR_NUMBER"
      - run: nvim --clean -es +"lua require('scripts.lintcommit').main({trace=true})"
