name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened]
jobs:

  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  type-scope:
    runs-on: ubuntu-latest
    needs: ["triage"]
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
      # Extract type and try to add it as a label
    - run: gh pr edit "$PR_NUMBER" --add-label "$(echo "$PR_TITLE" | sed -E 's|([[:alpha:]]+)(\(.*\))?!?:.*|\1|')" || true
      # Extract scope and try to add it as a label
    - run: gh pr edit "$PR_NUMBER" --add-label "$(echo "$PR_TITLE" | sed -E 's|[[:alpha:]]+\((.+)\)!?:.*|\1|')" || true

  add-reviewer:
    runs-on: ubuntu-latest
    needs: ["triage", "type-scope"]
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Get labels
        id: labels
        run: echo "::set-output name=labels::$(gh pr view $PR_NUMBER --json labels --jq '.labels.[].name' | tr '\n' '%')"

      - if: contains(steps.labels.outputs.labels, 'ci')
        run: echo "${{ steps.labels.outputs.labels }}"

      - if: contains(steps.labels.outputs.labels, 'lsp')
        run: gh pr edit $PR_NUMBER --add-reviewer mjlbach,mfussenegger || true

      - if: contains(steps.labels.outputs.labels, 'vim-patch')
        run: gh pr edit $PR_NUMBER --add-reviewer seandewar || true

      - if: contains(steps.labels.outputs.labels, 'diagnostic')
        run: gh pr edit $PR_NUMBER --add-reviewer gpanders || true

      - if: contains(steps.labels.outputs.labels, 'treesitter')
        run: gh pr edit $PR_NUMBER --add-reviewer bfredl || true
