name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened]
jobs:
  type-scope:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install -y python3 luajit
