name: "Linter"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  commits:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: nvim --clean -es +"lua require('scripts.lintcommit').main({trace=true})"

  gen-vimdoc:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install msgpack

      - run: scripts/gen_vimdoc.py

      - name: Check if any files have been changed
        run: git diff-index --quiet HEAD

